---

      ####### Play 1 #########
- name: Set up docker engine
  hosts: _Development
  become: yes                #If to escalate privilege
  become_method: sudo        #Set become method
  remote_user: centos          #Update username for remote server
  roles:
    - docker
  
      ########## Play 2 ##########
- name: Set up jenkins container
  hosts: _jenkinsserver
  become: yes
  become_method: sudo
  remote_user: centos
  become_user: root
  roles:
    - jenkins-setup

 ########## Play 3 ##########
- name: Set up kops machine
  hosts: _kubecontroller
  become: yes
  become_method: sudo
  remote_user: centos
  #become_user: root
  roles:
    - kube-setup
