---
# defaults file for jenkins-setup

# docker_compose_path: "../../compose_files"
docker_compose_dest: "/tmp/compose_files/"
jenkins_volume_path: "/home/{{ ansible_user }}/jenkins_compose/jenkins_configuration"