---
# defaults file for kube-setup

kubectl_base_url: "https://dl.k8s.io/release"
kubectl_url_bin_base: "/bin/linux/amd64/"
kubectl_bin_dest: "/usr/local/bin/kubectl"

kops_latest_release_url: "https://api.github.com/repos/kubernetes/kops/releases/latest"
kops_download_url_base: "https://github.com/kubernetes/kops/releases/download"
kops_bin_des: "/usr/local/bin/kops"

ssh_path: "/home/{{ ansible_user }}/.ssh/id_rsa"
aws_url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
aws_zip_dest: "./awscliv2.zip"
aws_bin_path: "/tmp"
aws_config_region: "us-east-2"
aws_config_format: "json"

domain_name: "kube.teslaacademic.online" ## must be the same as set in the cluster_domain_name variable in vars.tf
s3_bucket_url: "s3://trust-kops-state/kops-state" ## bucket name and object name MUST be the same as set in the vars.tf file
node_zones: "us-east-1a,us-east-1b"
number_of_nodes: 2
node_size: "t3.small"
master_size: "t3.medium"
node_volume: 8
master_volume: 8

helm_get_url: "https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3"
