---
# defaults file for kube-setup

kubectl_base_url: "https://dl.k8s.io/release"
kubectl_url_bin_base: "/bin/linux/amd64/"
kubectl_bin_dest: "/usr/local/bin/kubectl"

kops_latest_release_url: "https://api.github.com/repos/kubernetes/kops/releases/latest"
kops_download_url_base: "https://github.com/kubernetes/kops/releases/download"
kops_bin_des: "/usr/local/bin/kops"

ssh_path: "~/.ssh/"
aws_url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
aws_zip_dest: "./awscliv2.zip"
aws_tmp_dir: "/tmp/aws_dir"
aws_profile_name: "kubeadmin"
aws_region: "us-east-1"
aws_format: "json"