---
# tasks file for jenkins-setup

- name: copy Docker Compose files
  copy:
    src: "{{ docker_compose_path }}/{{ item }}"
    dest: "{{ docker_compose_dest }}/{{ item }}"
  loop:
  - jenkins-compose.yaml


- name: deploy Docker Compose stack
  shell:
    cmd: "docker compose -f jenkins-compose.yml -f up -d"
    chdir: "{{ docker_compose_dest }}"