---
# tasks file for jenkins-setup

- name: Create docker compose directory
  file:
    path: "{{ docker_compose_dest }}"
    state: directory
    mode: '0755'

- name: copy Docker Compose files
  template:
    src: jenkins-compose.yaml.j2
    dest: "{{ docker_compose_dest }}/jenkins-compose.yaml"


- name: deploy Docker Compose stack
  shell:
    cmd: "docker compose -f {{ docker_compose_dest }}/jenkins-compose.yaml up -d"


- name: Wait for Jenkins container to start
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 8080
    delay: 5
    timeout: 120

- name: Read admin passkey
  shell: "sudo cat {{ jenkins_volume_path }}/secrets/initialAdminPassword"
  register: jenkins_initial_password

- name: Display jenkins initial password contents
  debug:
    var: jenkins_initial_password