---
# tasks file for jenkins-setup

- name: Create docker compose directory
  file:
    path: "{{ docker_compose_dest }}"
    state: directory
    mode: '0755'

- name: copy Docker Compose files
  copy:
    src: "{{ docker_compose_path }}/{{ item }}"
    dest: "{{ docker_compose_dest }}/{{ item }}"
  loop:
  - jenkins-compose.yaml


- name: deploy Docker Compose stack
  shell:
    cmd: "docker compose -f jenkins-compose.yaml up -d"
    chdir: "{{ docker_compose_dest }}"

- name: Read admin passkey
  shell: cat "{{ jenkins_initial_pass_path }}"
  register: jenkins_initial_password

- name: Display jenkins initial password contents
  debug:
    var: jenkins_initial_password.stdout_lin