---
# tasks file for jenkins-setup

- name: copy Docker Compose files
  copy:
    src: "{{ docker_compose_path }}/{{ item }}"
    dest: "/home/{{ ansible_user }}/compose_files/{{ item }}"
  loop:
  - jenkins-compose.yaml


- name: deploy Docker Compose stack
  docker_compose:
    project_src: /home/{{ ansible_user }}/compose_files/
    files:
    - jenkins-compose.yaml