---

- name: Update cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

##### Debugging ################

- name: Print docker repo path
  debug:
    var: docker_repo_path

- name: Print docker url variable
  debug:
    var: docker_gpg_repo_url

- name: Print ansible_architecture variable
  debug:
    var: ansible_architecture

- name: Print ansible_distribution_release
  debug:
    var: ansible_distribution_release

- name: Print ansible_user
  debug:
    var: ansible_user


- name: Remove Docker if already available
  apt:
    name: ['docker.io', 'docker-doc', 'docker-compose', 'containerd', 'runc', 'podman-docker']
    state: absent
 

- name: Install apt utils
  apt:
    name: ['gnupg', 'curl', 'ca-certificates']
    state: present

- name: Create /etc/apt/keyrings directory
  file:
    path: "{{ docker_repo_dir }}"
    state: directory
    mode: '0755'

- name: Download Docker GPG key
  get_url:
    url: "{{ docker_gpg_repo_url }}/gpg"
    dest: "{{ docker_repo_path }}"

- name: Set permissions for Docker GPG key
  file:
    path: "{{ docker_repo_path }}"
    mode: '0644'

- name: Add Docker repository information to sources list
  lineinfile:
    path: /etc/apt/sources.list.d/docker.list
    line: 'deb [arch={{ ansible_architecture }} signed-by={{ docker_repo_path }}] {{ docker_gpg_repo_url }} {{ ansible_distribution_release }} stable'
    state: present
    create: yes
    insertafter: EOF

- name: Update cache
  apt:
    update_cache: yes

- name: Instal Docker and Plugins
  apt:
    name: ['docker-ce', 'docker-ce-cli', 'docker-buildx-plugin', 'docker-compose-plugin', 'containerd.io']
    state: present
  
- name: Add current user to the docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  notify: restart docker


