---

- name: Update cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Remove Docker if already available
  apt:
    name: ['docker.io', 'docker-doc', 'docker-compose', 'containerd', 'runc', 'podman-docker']
    state: absent
 

- name: Install apt utils
  apt:
    name: ['gnupg', 'curl', 'ca-certificates']
    state: present

- name: Create /etc/apt/keyrings directory
  file:
    path: "{{ docker_repo_dir }}"
    state: directory
    mode: '0755'


- name: Download Docker GPG key
  shell: curl -fsSL "{{ docker_gpg_repo_url }}/gpg" | sudo gpg --dearmor -o "{{ docker_repo_path }}"

- name: Set permissions for Docker GPG key
  shell: sudo chmod a+r "{{ docker_repo_path }}"


- name: Add Docker repository information
  shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by={{ docker_repo_path }}] {{ docker_gpg_repo_url }} \
    $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
    sudo tee /etc/apt/sources.list.d/docker.list > /dev/null


- name: Update cache
  apt:
    update_cache: yes

- name: Instal Docker and Plugins
  apt:
    name: ['docker-ce', 'docker-ce-cli', 'docker-buildx-plugin', 'docker-compose-plugin', 'containerd.io','unzip', 'git', 'java-1.8.0-openjdk']
    state: present
  
- name: Add current user to the docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  notify: restart docker


