---
# tasks file for kube-setup

- name: Include the vault password file
  include_vars:
    dir: vars/
    extensions: [yaml]

- include_tasks: set-up-awscli.yaml

- include_tasks: set-up-kube.yaml


