---
# tasks file for kube-setup

- name: Include the vault password file
  include_vars:
    - awscli_users.yaml
    - aws_secrets.yaml

- include_tasks: set-up-awscli.yaml

- include_tasks: set-up-kube.yaml


