---
# tasks file for kube-setup

- name: Generate an OpenSSH keypair with the default values (4096 bits, rsa)
  openssh_keypair:
    path: "{{ ssh_path }}"
  
- name: Extract AWS CLI zip package
  unarchive:
    src: "{{ aws_zip_dest }}"
    dest: "{{ aws_bin_path}}"
    remote_src: yes

- name: Install AWS CLI
  command: "{{ aws_bin_path }}/aws/install"


- name: Get current version of kubectl
  command: curl -L -s "{{ kubectl_base_url }}/stable.txt"
  register: kubectl_version_output

- name: Set kubectl version
  set_fact:
    kubectl_version: "{{ kubectl_version_output.stdout }}"

- name: Download AWS CLI zip package
  get_url:
    url: "{{ aws_url }}"
    dest: "{{ aws_zip_dest }}"


- name: Download kubectl
  get_url:
    url: "{{ kubectl_base_url }}/{{ kubectl_version }}/{{ kubectl_url_bin_base }}/kubectl"
    dest: "{{ kubectl_bin_dest }}"
    mode: "0755"
    owner: "root"
    group: "root"

- name: Get latest release JSON
  uri:
    url: "{{ kops_latest_release_url }}"
    return_content: yes
  register: release_response

- name: Extract tag name
  set_fact:
    kops_version: "{{ release_response.content | from_json | json_query('tag_name') }}"

- name: Print tag_name
  debug:
    var: kops_version

- name: Download kops binary
  get_url: 
    url: "{{ kops_download_url_base }}/{{ kops_version }}/kops-linux-amd64"
    dest: "/usr/local/bin/kops"
    mode: "0755"

